@startuml

class Communicator {
    - String access_token
    - Easy easy_handle
    + new(&self, access_token)
    + perform(url, type, headers, query, body, &result)
    + set_access_token(&self, access_token)
}

class Command {
    - Communicator communicator
    + new()
    + refresh(d_secret, refresh_token)
    + play(spotify_id)
    + pause()
    + next()
    + search(type, input, &result)
    + get_currently_playing(&result)
}

class lib {
    - Command command
    + new()
    + search_and_play_first(type : &str, search : &str) -> Result
    + search_playlist(search : &str, result : &mut Vec<String>) -> Result
    + search_album(search : &str, result : &mut Vec<Album>) -> Result
    + search_track(search : &str, result : &mut Vec<Track>) -> Result
    + search_artist(search : &str, result : &mut Vec<Artist>) -> Result
    + get_currently_playing_artist(result : &mut Artist) -> Result
    + get_currently_playing_track(result : &mut Track) -> Result
    + get_tracks_from_album(id: &str,result: &mut Vec<Track>) -> Result
    + get_my_albums(offset: u16, final_result: &mut Vec<Album>) -> Result
    + refresh() -> Result

}

class Files {
    + load_file()
}
main --> lib
lib --> Files
lib --> Command
Command --> Communicator
@enduml